version: '3.8'

services:
  redis:
    image: redis
#    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-tier
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server /usr/local/etc/redis/redis.conf --requirepass '$REDIS_PASSWORD'

  redis-cli:
    image: redislabs/redisinsight:latest
    restart: always
    depends_on:
      - redis
    networks:
      - app-tier
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    depends_on:
      - redis
    networks:
      - app-tier
    command:
      python app.py $REDIS_PASSWORD

networks:
  app-tier:
    driver: bridge

volumes:
  redisinsight: