version: '3.8'

services:
  redis:
    image: redis
#    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - app-tier
    environment:
#      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  redis-cli:
    image: redislabs/redisinsight:latest
    restart: always
    depends_on:
      - redis
    networks:
      - app-tier
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    depends_on:
      - redis
    networks:
      - app-tier
    command:
      python app.py

networks:
  app-tier:
    driver: bridge

volumes:
  redisinsight: